### ISSUE TITLE
the images in test_GT.zip are black in view

### ISSUE THREAD

**Issue by yinweizhuzhu** [val-iisc/sketch-parse#1]
![image](https://user-images.githubusercontent.com/17871048/30635550-558d05b6-9e25-11e7-836a-4566f3cb3323.png)

**Comment by isht7** [comment]
the labels of each class are given in [this](https://github.com/val-iisc/sketch-parse/blob/master/exp-src/data/sketch-dataset/Cls2Part.m) file. The labels are in the range of about 0 to 10 only, so they will look black if you look directly at them. You can visualize these images directly without any processing by using the matlab command `imagesc`
