### ISSUE TITLE
Requesting for Caffe folder

### ISSUE THREAD

**Issue by codaibk** [val-iisc/sketch-parse#3]
Hi, when i run "table1.py" with my caffe folder, it got this error "ImportError: /home/vipgpu/trang/caffe/python/caffe/../../build/lib/libcaffe.so.1.0.0: undefined symbol:_ZN5caffe20hdf5_load_nd_datasetIdEEvlPKciiPNS_4BlobIT_EEb"
Can you upload your your caffe folder which you used in this project?

Thanks

**Comment by isht7** [comment]
Hi, caffe is not used in our code. You can safely comment import caffe and then run the code. I will remove that particular line from the code.

**Comment by codaibk** [comment]
Oh, I got it. Thanks ^^

**Comment by isht7** [comment]
My apologies for this error, let me get back to you with this in some time.

**Comment by isht7** [comment]
I have added some files, pull the repo again and then run the file. Let me know if you encounter any additional problems.

**Comment by codaibk** [comment]
It seems it is ok now. Thank you ^^
