### ISSUE TITLE
Which model is the one that get the best performance?

### ISSUE THREAD

**Issue by zhengying1013** [val-iisc/sketch-parse#6]
Hi,

As you have uploaded too much models, I cannot tell which one is the model with the best performance. Can you tell me which one is the best? I think it should corresponds to the one named "BCP-R5" (63.17%) in Table 6 of your paper.

Thank you very much.

**Comment by ajdroid** [comment]
Please find the information here: 
https://github.com/val-iisc/sketch-parse/tree/master/exp-src

To train, we have:
> For BCP-R5, run
`python train_r5.py --segnetLoss --lambda1 1.0 --GTpath <train gt images path here> --IMpath <train images path here> `

If you just want to evaluate with our trained models, download them from [here](http://val.serc.iisc.ernet.in/star_snapshots/). Further instructions [here](https://github.com/val-iisc/sketch-parse/tree/master/exp-src).

**Comment by zhengying1013** [comment]
Thank you very much.
